### PR TITLE
Merge Ace changes from ajaxorg/ace

### PR DESCRIPTION
**Pull request by yanenkoa**

### CODE REVIEW

**Comment by dbarashev** [comment]
LGTM, in the hope that our master is really just a mirror of the upstream ace.

**Comment by yanenkoa** [comment]
@dbarashev it's actually not just a mirror. There are some changes in `ace/edit_session/bracket_match.js` to parse matching brackets, also some changes in JavaScript mode, which, I assume, came before I made a special Papeeria-branded LaTeX behaviour. There is also stuff like `ace/mode/latex_worker.js` and all that, which is added to our master compared to ajaxorg's. Some stuff is removed compared to ajaxorg's master, for instance, snippets and modes associated with "Red" (whatever this is).

**Comment by dbarashev** [comment]
@yanenkoa :( 
In order to make it actual mirror we'll have to remove our modifications and I believe that after master=>papeeria-master merge they will be removed in papeeria-master as well. However, if they merge fine with the current upstream, we can just merge, then find the diff between master and upstream and rebase the diff on top of papeeria-master. Does it make any sense?

**Comment by yanenkoa** [comment]
@dbarashev 

> after master=>papeeria-master merge they will be removed in papeeria-master as well

That depends on how we merge them though.

Also, what do you mean by "rebase the diff"? papeeria_master already has more up-to-date code than master.

**Comment by dbarashev** [comment]
@yanenkoa I mean, revert the diff between master and upstream, merge master into papeeria-master, apply the diff

**Comment by yanenkoa** [comment]
@dbarashev well I wanted to do just that. But `papeeria_master` already have everything in `master` plus a bunch more. So the last step "apply the diff" is not needed at all, and would probably mess up something.

**Comment by dbarashev** [comment]
@yanenkoa If you make master equal to upstream, you'll get diff comparing to papeeria-master where all our modifications will be removed. Subsequent merging of master to papeeria-master will apply the diff, and all our modifications will be removed from papeeria-master as well.
That's how I understand the work of diff and merge, but if my understanding is wrong and we will not lose anything from papeeria-master, that's the better

**Comment by yanenkoa** [comment]
@dbarashev no, we can merge alright no matter what. We can customize the merge however we want. Besides, if we use this logic, any merge from `master` to `papeeria_master` will remove changes in `papeeria_master`.

So, should I make our `master` equal to `ajaxorg/master`?

**Comment by dbarashev** [comment]
> So, should I make our master equal to ajaxorg/master?

Go ahead :)

**Comment by yanenkoa** [comment]
@dbarashev done, I only left `Makefile.papeeria` and stuff in `demo/` in this branch. Merging now.

**Pull request merged**
