### PR TITLE
Add mismatch highlighting

### PR DESCRIPTION
**Pull request by Pochatkin**
This marker may be appropriate? Or not?
@dbarashev

### CODE REVIEW

**Comment by dbarashev** [comment]
Can you try changing background of the whole mismatch text?

**Comment by Pochatkin** [comment]
Ok, i try.

**Comment by Pochatkin** [comment]
@dbarashev 
In this way?

**Comment by dbarashev** [comment]
Maybe expand range to the beginning/end of text if there is no left or right position?

**Comment by dbarashev** [comment]
Okay, let's leave it like this for now. I noticed that mismatch works fine unless the caret is at the very beginning of the row. If it is then mismatch is not shown, even when the caret seems to be in the mismatch range.

**Comment by Pochatkin** [comment]
@dbarashev 
This is because, @Mikhail-M add line of code ` if (position.column == 0) return {left: 0, right: 0, mismatch: true};`. I don't know why.

**Comment by dbarashev** [comment]
LGTM

**Pull request merged**
